--------------------------------------------------------
--  DDL for Table ADHERENT
--------------------------------------------------------

  CREATE TABLE "MATAOUI"."ADHERENT" 
   (	"ID_ADHERENT" VARCHAR2(10 BYTE), 
	"NOM" VARCHAR2(25 BYTE), 
	"PRENOM" VARCHAR2(25 BYTE), 
	"ID_POSITION" NUMBER, 
	"ID_CATEGORIE" VARCHAR2(100 BYTE), 
	"ETAT_ADHERENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
