--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "MATAOUI"."COMMANDE" 
   (	"NUM_COMMANDE" VARCHAR2(32 BYTE), 
	"OBSERVATION" VARCHAR2(256 BYTE), 
	"DATE_RECEPTION" DATE, 
	"MONTANT_GLOBAL" VARCHAR2(4000 BYTE), 
	"ID_FOURNISSEUR" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
