--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "MATAOUI"."FOURNISSEUR" 
   (	"ID_FOURNISSEUR" NUMBER, 
	"RAISON_SOCIALE" VARCHAR2(512 BYTE), 
	"ADRESSE" VARCHAR2(512 BYTE), 
	"NUM_TEL" VARCHAR2(128 BYTE), 
	"MAIL" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
