--------------------------------------------------------
--  DDL for Table MENTION_RESPONSABILITE
--------------------------------------------------------

  CREATE TABLE "MATAOUI"."MENTION_RESPONSABILITE" 
   (	"ID_MENTION_RES" NUMBER(38,0), 
	"NOM" VARCHAR2(255 BYTE), 
	"AUTRE_PARTIE" VARCHAR2(255 BYTE), 
	"COLLECTIVITE" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
