--------------------------------------------------------
--  DDL for Table NOTICE_DIP_DIS_ETAB
--------------------------------------------------------

  CREATE TABLE "MATAOUI"."NOTICE_DIP_DIS_ETAB" 
   (	"ID_DIPLOME" NUMBER(38,0), 
	"ID_ETABLISSEMENT" NUMBER(38,0), 
	"ID_DISCIPLINE" NUMBER(38,0), 
	"ID_NOTICE" NUMBER(38,0), 
	"NOTE_TEXTE" VARCHAR2(255 BYTE), 
	"ANNE_SOUTENANCE" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
