--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "MATAOUI"."NOTICE" 
   (	"ID_NOTICE" NUMBER(38,0), 
	"ID_SOURCE_ARTICLE" NUMBER(38,0), 
	"ID_TYPE" NUMBER(38,0), 
	"ID_PERIODICITE" VARCHAR2(2 BYTE), 
	"TITRE_PROPRE" VARCHAR2(512 BYTE), 
	"SOUS_TITRE" VARCHAR2(512 BYTE), 
	"N_PARTIE" VARCHAR2(255 BYTE), 
	"COLLATION_IMP_MATERIELLE" VARCHAR2(50 BYTE), 
	"COLLATION_AUTRES_CAR_MAT" VARCHAR2(50 BYTE), 
	"COLLATION_FORMAT" VARCHAR2(50 BYTE), 
	"NBR_EXEMPLE" NUMBER(38,0), 
	"COTE" VARCHAR2(25 BYTE), 
	"LOCALISATION" VARCHAR2(255 BYTE), 
	"CDD" VARCHAR2(15 BYTE), 
	"RESUME" VARCHAR2(2048 BYTE), 
	"ISBN" VARCHAR2(255 BYTE), 
	"DATE_1ER_PUB" VARCHAR2(50 BYTE), 
	"TITRE_CLE" VARCHAR2(255 BYTE), 
	"NUMERO_VOL" VARCHAR2(50 BYTE), 
	"ISSN_NOTICE" VARCHAR2(50 BYTE), 
	"NOTE_GENERALE" VARCHAR2(255 BYTE), 
	"IS_INDEXED" NUMBER(38,0), 
	"ACCESSIBILITE" VARCHAR2(1 BYTE) DEFAULT 1, 
	"EXEMPLAIRE_EXISTE" NUMBER DEFAULT 0, 
	"TYPE_DONNEES_RESOURCE_ELEC" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
