--------------------------------------------------------
--  DDL for Table SOURCE_ARTICLE
--------------------------------------------------------

  CREATE TABLE "MATAOUI"."SOURCE_ARTICLE" 
   (	"ID_SOURCE_ARTICLE" NUMBER(38,0), 
	"TITRE_SOURCE_ARTICLE" VARCHAR2(255 BYTE), 
	"DATE_PUB_ARTICLE" VARCHAR2(25 BYTE), 
	"INTERVALE_PAGE" VARCHAR2(25 BYTE), 
	"NUMERO_REVUE" VARCHAR2(20 BYTE), 
	"ISSN_REVUE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
