--------------------------------------------------------
--  DDL for Table UTILISATEUR
--------------------------------------------------------

  CREATE TABLE "MATAOUI"."UTILISATEUR" 
   (	"COMPTE" VARCHAR2(20 BYTE), 
	"MOTDEPASSE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"COLUMN1" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"DATECRERATIONCOMPTE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
