services:
  oracle-db:
    build: .                          
    container_name: oracle-database
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=fadelakram
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: