ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER MATAOUI IDENTIFIED BY mataoui123
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO MATAOUI;