--------------------------------------------------------
--  Constraints for Table AQUISITION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."AQUISITION" ADD CONSTRAINT "AQUISITION_PK" PRIMARY KEY ("NUM_COMMANDE", "ID_EXEMPLAIRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MATAOUI"."AQUISITION" MODIFY ("NUM_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."AQUISITION" MODIFY ("ID_EXEMPLAIRE" NOT NULL ENABLE);
