--------------------------------------------------------
--  Constraints for Table AUTEUR_SECONDAIRE
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."AUTEUR_SECONDAIRE" ADD CONSTRAINT "PK_AUTEUR_SECONDAIRE" PRIMARY KEY ("ID_NOTICE", "ID_MENTION_RES", "ID_FONCTION")
  USING INDEX "MATAOUI"."PK_AUTEUR_SECONDAIRE"  ENABLE;
  ALTER TABLE "MATAOUI"."AUTEUR_SECONDAIRE" MODIFY ("ID_NOTICE" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."AUTEUR_SECONDAIRE" MODIFY ("ID_MENTION_RES" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."AUTEUR_SECONDAIRE" MODIFY ("ID_FONCTION" NOT NULL ENABLE);
