--------------------------------------------------------
--  Constraints for Table HISTORIQUE_AUTH
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."HISTORIQUE_AUTH" ADD CONSTRAINT "HISTORIQUE_AUTH_PK" PRIMARY KEY ("ID_ADMIN", "DATE_OPERATION", "ID_ADHERENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MATAOUI"."HISTORIQUE_AUTH" MODIFY ("ID_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."HISTORIQUE_AUTH" MODIFY ("DATE_OPERATION" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."HISTORIQUE_AUTH" MODIFY ("ID_ADHERENT" NOT NULL ENABLE);
