--------------------------------------------------------
--  Constraints for Table MENTION_RESPONSABILITE
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."MENTION_RESPONSABILITE" ADD CONSTRAINT "PK_MENTION_RESPONSABILITE" PRIMARY KEY ("ID_MENTION_RES")
  USING INDEX "MATAOUI"."PK_MENTION_RESPONSABILITE"  ENABLE;
  ALTER TABLE "MATAOUI"."MENTION_RESPONSABILITE" MODIFY ("ID_MENTION_RES" NOT NULL ENABLE);
