--------------------------------------------------------
--  Constraints for Table MENTION_EDITION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."MENTION_EDITION" ADD CONSTRAINT "MENTION_EDITION_PK" PRIMARY KEY ("ID_NOTICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MATAOUI"."MENTION_EDITION" MODIFY ("ID_NOTICE" NOT NULL ENABLE);
