--------------------------------------------------------
--  Constraints for Table MENTION_RES_COLLECTION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."MENTION_RES_COLLECTION" ADD CONSTRAINT "PK_MENTION_RES_COLLECTION" PRIMARY KEY ("ID_COLLECTION", "ID_MENTION_RES")
  USING INDEX "MATAOUI"."PK_MENTION_RES_COLLECTION"  ENABLE;
  ALTER TABLE "MATAOUI"."MENTION_RES_COLLECTION" MODIFY ("ID_COLLECTION" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."MENTION_RES_COLLECTION" MODIFY ("ID_MENTION_RES" NOT NULL ENABLE);
