--------------------------------------------------------
--  Constraints for Table MOTS_CLES
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."MOTS_CLES" ADD CONSTRAINT "PK_MOTS_CLES" PRIMARY KEY ("ID_MOT_CLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MATAOUI"."MOTS_CLES" MODIFY ("ID_MOT_CLE" NOT NULL ENABLE);
