--------------------------------------------------------
--  Constraints for Table NOTICE_COLLECTION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE_COLLECTION" ADD CONSTRAINT "PK_NOTICE_COLLECTION" PRIMARY KEY ("ID_NOTICE", "ID_COLLECTION")
  USING INDEX "MATAOUI"."PK_NOTICE_COLLECTION"  ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_COLLECTION" MODIFY ("ID_NOTICE" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."NOTICE_COLLECTION" MODIFY ("ID_COLLECTION" NOT NULL ENABLE);
