--------------------------------------------------------
--  Constraints for Table NOTICE_MENTION_EDITION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE_MENTION_EDITION" ADD CONSTRAINT "NOTICE_MENTION_EDITION_PK" PRIMARY KEY ("ID_NOTICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_MENTION_EDITION" MODIFY ("ID_NOTICE" NOT NULL ENABLE);
