--------------------------------------------------------
--  Constraints for Table NOTICE_DIP_DIS_ETAB
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE_DIP_DIS_ETAB" ADD CONSTRAINT "PK_NOTICE_DIP_DIS_ETAB" PRIMARY KEY ("ID_NOTICE")
  USING INDEX "MATAOUI"."PK_NOTICE_DIP_DIS_ETAB"  ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_DIP_DIS_ETAB" MODIFY ("ID_DIPLOME" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."NOTICE_DIP_DIS_ETAB" MODIFY ("ID_ETABLISSEMENT" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."NOTICE_DIP_DIS_ETAB" MODIFY ("ID_DISCIPLINE" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."NOTICE_DIP_DIS_ETAB" MODIFY ("ID_NOTICE" NOT NULL ENABLE);
