--------------------------------------------------------
--  Constraints for Table NOTICE_EDITION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE_EDITION" ADD CONSTRAINT "PK_NOTICE_EDITION" PRIMARY KEY ("ID_VILLE", "ID_EDITEUR", "ID_NOTICE")
  USING INDEX "MATAOUI"."PK_NOTICE_EDITION"  ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_EDITION" MODIFY ("ID_VILLE" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."NOTICE_EDITION" MODIFY ("ID_EDITEUR" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."NOTICE_EDITION" MODIFY ("ID_NOTICE" NOT NULL ENABLE);
