--------------------------------------------------------
--  Constraints for Table NOTICE_TERME
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE_TERME" ADD CONSTRAINT "PK_NOTICE_TERME" PRIMARY KEY ("ID_TERME", "ID_NOTICE")
  USING INDEX "MATAOUI"."PK_NOTICE_TERME"  ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_TERME" MODIFY ("ID_TERME" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."NOTICE_TERME" MODIFY ("ID_NOTICE" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."NOTICE_TERME" MODIFY ("POIDS_TERME" NOT NULL ENABLE);
