--------------------------------------------------------
--  Constraints for Table PAYS_PUBLICATION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."PAYS_PUBLICATION" ADD CONSTRAINT "PK_PAYS_PUBLICATION" PRIMARY KEY ("ID_NOTICE", "ID_PAYS")
  USING INDEX "MATAOUI"."PK_PAYS_PUBLICATION"  ENABLE;
  ALTER TABLE "MATAOUI"."PAYS_PUBLICATION" MODIFY ("ID_NOTICE" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."PAYS_PUBLICATION" MODIFY ("ID_PAYS" NOT NULL ENABLE);
