--------------------------------------------------------
--  Constraints for Table PENALITE_ADHERENT
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."PENALITE_ADHERENT" ADD CONSTRAINT "PENALITE_ADHERENT_PK" PRIMARY KEY ("ID_ADHERENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MATAOUI"."PENALITE_ADHERENT" MODIFY ("ID_ADHERENT" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."PENALITE_ADHERENT" MODIFY ("DATE_PENALITE" NOT NULL ENABLE);
