--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("ID_ADHERENT", "COTE", "HEURE_RESERVATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MATAOUI"."RESERVATION" MODIFY ("ID_ADHERENT" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."RESERVATION" MODIFY ("COTE" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."RESERVATION" MODIFY ("HEURE_RESERVATION" NOT NULL ENABLE);
