--------------------------------------------------------
--  Constraints for Table TERME_EXACT
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."TERME_EXACT" MODIFY ("ID_TERME_EXACT" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."TERME_EXACT" ADD CONSTRAINT "TERME_EXACT_PK" PRIMARY KEY ("ID_TERME_EXACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
