--------------------------------------------------------
--  Constraints for Table THEME
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."THEME" ADD CONSTRAINT "PK_THEME" PRIMARY KEY ("ID_THEME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MATAOUI"."THEME" MODIFY ("ID_THEME" NOT NULL ENABLE);
