--------------------------------------------------------
--  Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."UTILISATEUR" MODIFY ("COMPTE" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."UTILISATEUR" MODIFY ("MOTDEPASSE" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."UTILISATEUR" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."UTILISATEUR" MODIFY ("COLUMN1" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."UTILISATEUR" MODIFY ("DATECRERATIONCOMPTE" NOT NULL ENABLE);
  ALTER TABLE "MATAOUI"."UTILISATEUR" ADD CONSTRAINT "UTILISATEUR_PK" PRIMARY KEY ("COMPTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
