--------------------------------------------------------
--  Ref Constraints for Table AUTEUR_SECONDAIRE
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."AUTEUR_SECONDAIRE" ADD CONSTRAINT "FK_AUTEUR_S_LIEN_138_NOTICE" FOREIGN KEY ("ID_NOTICE")
	  REFERENCES "MATAOUI"."NOTICE" ("ID_NOTICE") ON DELETE CASCADE DISABLE;
  ALTER TABLE "MATAOUI"."AUTEUR_SECONDAIRE" ADD CONSTRAINT "FK_AUTEUR_S_LIEN_143_MENTION_" FOREIGN KEY ("ID_MENTION_RES")
	  REFERENCES "MATAOUI"."MENTION_RESPONSABILITE" ("ID_MENTION_RES") ENABLE;
  ALTER TABLE "MATAOUI"."AUTEUR_SECONDAIRE" ADD CONSTRAINT "FK_AUTEUR_S_LIEN_161_FONCTION" FOREIGN KEY ("ID_FONCTION")
	  REFERENCES "MATAOUI"."FONCTION" ("ID_FONCTION") ENABLE;
