--------------------------------------------------------
--  Ref Constraints for Table AUTEUR
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."AUTEUR" ADD CONSTRAINT "FK_AUTEUR_LIEN_140_NOTICE" FOREIGN KEY ("ID_NOTICE")
	  REFERENCES "MATAOUI"."NOTICE" ("ID_NOTICE") ON DELETE CASCADE DISABLE;
  ALTER TABLE "MATAOUI"."AUTEUR" ADD CONSTRAINT "FK_AUTEUR_LIEN_141_MENTION_" FOREIGN KEY ("ID_MENTION_RES")
	  REFERENCES "MATAOUI"."MENTION_RESPONSABILITE" ("ID_MENTION_RES") ENABLE;
