--------------------------------------------------------
--  Ref Constraints for Table CO_AUTEUR
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."CO_AUTEUR" ADD CONSTRAINT "FK_CO_AUTEU_LIEN_139_NOTICE" FOREIGN KEY ("ID_NOTICE")
	  REFERENCES "MATAOUI"."NOTICE" ("ID_NOTICE") ON DELETE CASCADE DISABLE;
  ALTER TABLE "MATAOUI"."CO_AUTEUR" ADD CONSTRAINT "FK_CO_AUTEU_LIEN_142_MENTION_" FOREIGN KEY ("ID_MENTION_RES")
	  REFERENCES "MATAOUI"."MENTION_RESPONSABILITE" ("ID_MENTION_RES") ENABLE;
