--------------------------------------------------------
--  Ref Constraints for Table HISTORIQUE_AUTH
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."HISTORIQUE_AUTH" ADD CONSTRAINT "HISTORIQUE_AUTH_ADHERENT_FK1" FOREIGN KEY ("ID_ADHERENT")
	  REFERENCES "MATAOUI"."ADHERENT" ("ID_ADHERENT") ENABLE;
  ALTER TABLE "MATAOUI"."HISTORIQUE_AUTH" ADD CONSTRAINT "HISTORIQUE_AUTH_OPERATION_FK1" FOREIGN KEY ("ID_TYPE_OPERATION")
	  REFERENCES "MATAOUI"."OPERATION" ("ID_OPERATION") ENABLE;
