--------------------------------------------------------
--  Ref Constraints for Table MENTION_RES_COLLECTION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."MENTION_RES_COLLECTION" ADD CONSTRAINT "FK_MENTION__LIEN_163_COLLECTI" FOREIGN KEY ("ID_COLLECTION")
	  REFERENCES "MATAOUI"."COLLECTION" ("ID_COLLECTION") ENABLE;
  ALTER TABLE "MATAOUI"."MENTION_RES_COLLECTION" ADD CONSTRAINT "FK_MENTION__LIEN_164_MENTION_" FOREIGN KEY ("ID_MENTION_RES")
	  REFERENCES "MATAOUI"."MENTION_RESPONSABILITE" ("ID_MENTION_RES") ENABLE;
