--------------------------------------------------------
--  Ref Constraints for Table NOTICE_DIP_DIS_ETAB
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE_DIP_DIS_ETAB" ADD CONSTRAINT "FK_NOTICE_D_LIEN_155_DIPLOME" FOREIGN KEY ("ID_DIPLOME")
	  REFERENCES "MATAOUI"."DIPLOME" ("ID_DIPLOME") ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_DIP_DIS_ETAB" ADD CONSTRAINT "FK_NOTICE_D_LIEN_156_ETABLISS" FOREIGN KEY ("ID_ETABLISSEMENT")
	  REFERENCES "MATAOUI"."ETABLISSEMENT" ("ID_ETABLISSEMENT") ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_DIP_DIS_ETAB" ADD CONSTRAINT "FK_NOTICE_D_LIEN_157_DISCIPLI" FOREIGN KEY ("ID_DISCIPLINE")
	  REFERENCES "MATAOUI"."DISCIPLINE" ("ID_DISCIPLINE") ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_DIP_DIS_ETAB" ADD CONSTRAINT "FK_NOTICE_D_LIEN_158_NOTICE" FOREIGN KEY ("ID_NOTICE")
	  REFERENCES "MATAOUI"."NOTICE" ("ID_NOTICE") ON DELETE CASCADE DISABLE;
