--------------------------------------------------------
--  Ref Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE" ADD CONSTRAINT "FK_NOTICE_ASSOC_379_TYPE_NOT" FOREIGN KEY ("ID_TYPE")
	  REFERENCES "MATAOUI"."TYPE_NOTICE" ("ID_TYPE") ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE" ADD CONSTRAINT "FK_NOTICE_ASSOC_513_PERIODIC" FOREIGN KEY ("ID_PERIODICITE")
	  REFERENCES "MATAOUI"."PERIODICITE" ("ID_PERIODICITE") ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE" ADD CONSTRAINT "FK_NOTICE_NOTICE_SO_SOURCE_A" FOREIGN KEY ("ID_SOURCE_ARTICLE")
	  REFERENCES "MATAOUI"."SOURCE_ARTICLE" ("ID_SOURCE_ARTICLE") DISABLE;
  ALTER TABLE "MATAOUI"."NOTICE" ADD CONSTRAINT "NOTICE_TABLE_CDD_FK1" FOREIGN KEY ("CDD")
	  REFERENCES "MATAOUI"."TABLE_CDD" ("CDD") ON DELETE SET NULL DISABLE;
