--------------------------------------------------------
--  Ref Constraints for Table NOTICE_MOT_CLE
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE_MOT_CLE" ADD CONSTRAINT "FK_NOTICE_M_LIEN_159_NOTICE" FOREIGN KEY ("ID_NOTICE")
	  REFERENCES "MATAOUI"."NOTICE" ("ID_NOTICE") ON DELETE CASCADE DISABLE;
  ALTER TABLE "MATAOUI"."NOTICE_MOT_CLE" ADD CONSTRAINT "FK_NOTICE_M_LIEN_160_MOTS_CLE" FOREIGN KEY ("ID_MOT_CLE")
	  REFERENCES "MATAOUI"."MOTS_CLES" ("ID_MOT_CLE") ENABLE;
