--------------------------------------------------------
--  Ref Constraints for Table NOTICE_EDITION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE_EDITION" ADD CONSTRAINT "FK_NOTICE_E_LIEN_898_VILLE" FOREIGN KEY ("ID_VILLE")
	  REFERENCES "MATAOUI"."VILLE" ("ID_VILLE") ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_EDITION" ADD CONSTRAINT "FK_NOTICE_E_LIEN_899_EDITEUR" FOREIGN KEY ("ID_EDITEUR")
	  REFERENCES "MATAOUI"."EDITEUR" ("ID_EDITEUR") ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_EDITION" ADD CONSTRAINT "FK_NOTICE_E_LIEN_900_NOTICE" FOREIGN KEY ("ID_NOTICE")
	  REFERENCES "MATAOUI"."NOTICE" ("ID_NOTICE") ON DELETE CASCADE ENABLE;
