--------------------------------------------------------
--  Ref Constraints for Table NOTICE_COLLECTION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE_COLLECTION" ADD CONSTRAINT "FK_NOTICE_C_LIEN_144_NOTICE" FOREIGN KEY ("ID_NOTICE")
	  REFERENCES "MATAOUI"."NOTICE" ("ID_NOTICE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_COLLECTION" ADD CONSTRAINT "FK_NOTICE_C_LIEN_145_COLLECTI" FOREIGN KEY ("ID_COLLECTION")
	  REFERENCES "MATAOUI"."COLLECTION" ("ID_COLLECTION") ENABLE;
