--------------------------------------------------------
--  Ref Constraints for Table NOTICE_TERME
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE_TERME" ADD CONSTRAINT "FK_NOTICE_T_LIEN_507_TERME" FOREIGN KEY ("ID_TERME")
	  REFERENCES "MATAOUI"."TERME" ("ID_TERME") ENABLE;
  ALTER TABLE "MATAOUI"."NOTICE_TERME" ADD CONSTRAINT "FK_NOTICE_T_LIEN_508_NOTICE" FOREIGN KEY ("ID_NOTICE")
	  REFERENCES "MATAOUI"."NOTICE" ("ID_NOTICE") ON DELETE CASCADE DISABLE;
