--------------------------------------------------------
--  Ref Constraints for Table NOTICE_LANGUE
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."NOTICE_LANGUE" ADD CONSTRAINT "FK_NOTICE_L_LIEN_152_NOTICE" FOREIGN KEY ("ID_NOTICE")
	  REFERENCES "MATAOUI"."NOTICE" ("ID_NOTICE") ON DELETE CASCADE DISABLE;
  ALTER TABLE "MATAOUI"."NOTICE_LANGUE" ADD CONSTRAINT "FK_NOTICE_L_LIEN_153_LANGUE" FOREIGN KEY ("ID_LANGUE")
	  REFERENCES "MATAOUI"."LANGUE" ("ID_LANGUE") ENABLE;
