--------------------------------------------------------
--  Ref Constraints for Table PAYS_PUBLICATION
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."PAYS_PUBLICATION" ADD CONSTRAINT "FK_PAYS_PUB_LIEN_148_NOTICE" FOREIGN KEY ("ID_NOTICE")
	  REFERENCES "MATAOUI"."NOTICE" ("ID_NOTICE") ON DELETE CASCADE DISABLE;
  ALTER TABLE "MATAOUI"."PAYS_PUBLICATION" ADD CONSTRAINT "FK_PAYS_PUB_LIEN_149_PAYS" FOREIGN KEY ("ID_PAYS")
	  REFERENCES "MATAOUI"."PAYS" ("ID_PAYS") ENABLE;
