--------------------------------------------------------
--  Ref Constraints for Table SELECTION_NOTICE
--------------------------------------------------------

  ALTER TABLE "MATAOUI"."SELECTION_NOTICE" ADD CONSTRAINT "SELECTION_NOTICE_NOTICE_FK1" FOREIGN KEY ("ID_NOTICE")
	  REFERENCES "MATAOUI"."NOTICE" ("ID_NOTICE") ENABLE;
  ALTER TABLE "MATAOUI"."SELECTION_NOTICE" ADD CONSTRAINT "SELECTION_NOTICE_SELECTIO_FK1" FOREIGN KEY ("ID_SELECTION")
	  REFERENCES "MATAOUI"."SELECTION" ("ID_SELECTION") ENABLE;
