<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Borrowing.Worker-5eba8790-f3b2-4dec-8eed-40b7ddf8cbe5</UserSecretsId>
    <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    <!-- <NoWarn>CA1812</NoWarn> -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Common.csproj" />
  </ItemGroup>
</Project>
