--------------------------------------------------------
--  DDL for Index HISTORIQUE_PENALITE_ADHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATAOUI"."HISTORIQUE_PENALITE_ADHER_PK" ON "MATAOUI"."HISTORIQUE_PENALITE_ADHERENT" ("ID_ADHERENT", "DATE_PENALITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
