--------------------------------------------------------
--  DDL for Index PK_CO_AUTEUR
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATAOUI"."PK_CO_AUTEUR" ON "MATAOUI"."CO_AUTEUR" ("ID_NOTICE", "ID_MENTION_RES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
