--------------------------------------------------------
--  DDL for Index PK_DIPLOME
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATAOUI"."PK_DIPLOME" ON "MATAOUI"."DIPLOME" ("ID_DIPLOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
