<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  
  <ItemGroup>
    <ProjectReference Include="..\Borrowing.SharedClasses\Borrowing.SharedClasses.csproj" />
  </ItemGroup>

  
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Radzen.Blazor" Version="10.0.3" />
  </ItemGroup>
</Project>
